### ISSUE TITLE
Remove properties?

### ISSUE THREAD

**Issue by rowanc1** [simpeg/geoana#28]
@jcapriot @lheagy I was looking through some of the code and couldn't find properties references in some of the new stuff - it would be great if we could remove this completely! Is in now just in oksar? If so we could maybe put that on a branch and remove it from the main repo?

I was playing around with JupyterLite which runs completely in the browser, this would be a great target to be able to run/compute and plot these sort of examples interactively! :)

**Comment by lheagy** [comment]
:+1: Agreed, it would be nice to remove! I think it is still hanging around in the em side of things as well: https://github.com/simpeg/geoana/blob/main/geoana/em/base.py#L15

So might be worth a pass to try and get it out everywhere. @jcapriot: I know you went through this in discretize. Is it something you think we could outline and have someone else work on?

**Comment by lheagy** [comment]
this will close with #31. Nice work @dccowan 🚀

**Comment by lheagy** [comment]
closed with merge of #31. Many thanks @dccowan and @jcapriot!
