### ISSUE TITLE
earthquake/oskar - UidModel 

### ISSUE THREAD

**Issue by lheagy** [simpeg/geoana#3]
`EarthquakeInterferogram` is currently inheriting `properties.UidModel` which no longer exists?

**Comment by rowanc1** [comment]
I think there is now a `Uuid` parameter?

I think that really this should be name. (but isn't really even necessary in this context).

**Comment by lheagy** [comment]
it should just be inheriting `properties.HasProperties`??

**Comment by rowanc1** [comment]
Yep.

**Comment by rowanc1** [comment]
It should not even change the example:

![image](https://cloud.githubusercontent.com/assets/913249/21362265/caea608c-c6a4-11e6-9751-1bfd64ad98d4.png)
