### ISSUE TITLE
Installing from conda gives unexpected import errors

### ISSUE THREAD

**Issue by stevejpurves** [simpeg/geoana#30]
When I install from conda forge is reportedly get a version `0.1.2` both in terms of `conda list` and when doing:

```
import geoana
print(geoana.__version__)
```

However, the following import statement then fails in my code:
```
from geoana.em.static import ElectrostaticSphere

...

NameError: name 'ElectrostaticSphere' is not defined
```

If I install the latest package from `pip` this is not the case.

When uninstalling the `conda` version I noticed:

```
  removed specs:
    - geoana

The following packages will be REMOVED:

  future-0.18.2-py39h2804cbe_4
  geoana-0.0.6-py_1
  properties-0.6.1-py_0
  utm-0.7.0-pyhd8ed1ab_0
  vectormath-0.2.2-py_0

Proceed ([y]/n)? y
```

Is this released with the wrong wheel/build?

This has happened on both MacOS/Apple Silicon (which i can maybe understand), and on AWS EC2 instance with Ubuntu 18

**Comment by jcapriot** [comment]
For what it's worth, what happened was the `geoana` was downgraded to the last noarch version because that's what was available on conda-forge for your system. It now includes builds for all of the architectures supported by conda-forge.
