### ISSUE TITLE
Circular import on last release

### ISSUE THREAD

**Issue by domfournier** [simpeg/geoana#37]
Hey gang, we started getting this error message on the last release.
Thoughts?

![image](https://user-images.githubusercontent.com/55204635/166491931-5e913465-0e7a-44d8-b3fa-6bc85d38fef6.png)

**Comment by domfournier** [comment]
Issue only arise for older simpeg < 0.17. Closing this

**Comment by jcapriot** [comment]
I think this actually boiled down to an improper distribution of the source code to PyPI. I've bumped the version and ensured that the static module is in fact included.
