### ISSUE TITLE
Gravity due to a point mass & sphere

### ISSUE THREAD

**Issue by jcapriot** [simpeg/geoana#39]
We should add the simple solutions for the gravitational potential, field, and even the gravity gradient due to a simple point mass. The formulas should be straightforward enough to implement!

```
U_g = G * m/ r

g_vec = -G *m *r_vec/ r**3

gg_tens = -G * m * (eye /r**3 - 3 * outer(r_vec, r_vec) / r**5)
```
etc..

This could then be extended for a sphere,

**Comment by lheagy** [comment]
where do you think this should live @jcapriot? `geoana/potential_fields/gravity.py`?

**Comment by jcapriot** [comment]
Sounds like a great place!

**Comment by jcapriot** [comment]
The only question is... do we decide the relationship between gravity and it's potential is `g = -\nabla U` or `g=\nabla U`...

**Comment by lheagy** [comment]
I would be inclined to follow Blakely on this and use g = \nabla U

**Comment by lheagy** [comment]
@Syckdog, would you be willing to give this a go?

**Comment by lheagy** [comment]
One other note is that `scipy.constants` includes G, so we can make use of that: https://docs.scipy.org/doc/scipy/reference/constants.html
