### ISSUE TITLE
test coverage for `LineCurrentFreeSpace`

### ISSUE THREAD

**Issue by lheagy** [simpeg/geoana#44]
It appears that the only testing for the LineCurrentFreeSpace is just in the documentation, it would be good to have tests that check accuracy as well. Here are a couple of ideas: 
- use a small segment (1m) and compare with the electric dipole in a whole space (away from that) 
- use a small closed loop (say 1m x 1m) and compare with a magnetic dipole in a whole space (again away from it)

It will take a bit of care to choose appropriate distances and tolerances, but I suspect that at about 10m the solutions should be nearly identical, and these could be tested for each orientation

**Comment by jcapriot** [comment]
addressed in #76
